---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mateusdutra-tp2-song-v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mateusdutra-tp2-song
  template:
    metadata:
      labels:
        app: mateusdutra-tp2-song
    spec:
      containers:
      - name: mateusdutra-tp2-song-ml
        image: quay.io/mmdutra14/mateusdutra-tp2-song-ml
        imagePullPolicy: Always
        env:
        - name: MIN_CONFIDENCE
          value: "0.1"
        - name: MIN_SUPPORT_RATIO
          value: "0.1"
        volumeMounts:
        - name: shared-volume
          mountPath: /app/data
    
      volumes:
        - name: shared-volume
          persistentVolumeClaim:
            claimName: mateusdutra-tp2-song-pvc